### ISSUE TITLE
Nav Controller and DPC Latency Issues

### ISSUE THREAD

**Issue by Encryption767** [nefarius/FireShock#4] opened 2016-10-08 12:12 UTC
Would it be possible for you to support the PS3 Move nav controller with these drivers? Or maybe make them recognized as a ds4 to be picked up in DS4Windows for the auto profiler it has. 

I have used it with scptoolkit but there is no direct input only or convert to direct input option and the profiler has always been broken. 

Excellent controller to use with FPS games in combination with a mouse like the g600 or naga, especially when your PC is in the living room and not on a desk (eliminates having to keep a keyboard in your lap),, but just can't seem to find any software what would let me map the whole controller out to kb or kb and xinput hybrid for the axis.

**Comment by nefarius** [comment] 2016-10-08 14:03
If I'd have one or at least a machine with one connected then sure I could 😄

**Comment by mirh** [comment] 2016-10-08 19:16
thp/psmoveapi#185
For as much.. I dunno, it'd feel both weird and wrong to have two open source drivers for the same device.

**Comment by nefarius** [comment] 2016-10-08 19:17
Oh, if there already is one I don't wanna interfer 😃

**Comment by Encryption767** [comment] 2016-10-08 20:09
Wasn't able to do anything with thp/psmoveapi#185. Think that is a lib being made for other programs to incorporate?

Anyways, nefarius has software already that lets one connect and work perfectly with xinput with the scptoolkit. Unfortunately, there are games out there that for some silly reason will not allow a controller/kb/mouse combo. Without being able to turn off the virtual 360 driver and just map the controller to keybinds instead then it can't be used. It works out that you have to have either or and aiming with a thumb stick sucks balls.

He has a very simple driver here though. I thought it would be nice to see a nav controller connect and stay connected so maybe it can be mapped with something like xpadder or antimicro.

**Comment by nefarius** [comment] 2016-10-08 20:10
@Encryption767 if you force it over your controller via Device manager does it work?

**Comment by Encryption767** [comment] 2016-10-08 20:12
Scptoolkit or FireShock? Trying to install Fireshock to the navigation controller entry in the device manager ends with with a power failure code.

**Comment by nefarius** [comment] 2016-10-08 20:13
Ah I see 😆

**Comment by nefarius** [comment] 2016-10-08 20:13
Well if I'd have one I'd gladly take a look. I always accept hardware gifts though 😉

**Comment by Encryption767** [comment] 2016-10-08 20:14
USB\VID_054C&PID_042F&REV_0100
USB\VID_054C&PID_042F

Hardware ids. 

You could probably grab one for $5 at gamestop lol.

**Comment by nefarius** [comment] 2016-10-08 20:16
I'm already devoting a **lot** of time and knowledge to my free and open source projects but I fail to see why **I** should also buy the hardware to analyze 😉

**Comment by Encryption767** [comment] 2016-10-08 20:16
It connects perfectly to SCPtoolkit. Great work with that btw. If SCPtoolkit had the ability to just spit raw data or map to directinput or xinput instead of xinput or nothing and had a good profiler then I could drop ds4windows and just use scptk for my ps controllers :P

**Comment by Encryption767** [comment] 2016-10-08 20:21
If you were in the states then I would.

**Comment by mirh** [comment] 2016-10-08 22:49
> Oh, if there already is one I don't wanna interfer

Not that I think you should really bother with this, given we are all lusting over polished fireshock and airbender.. But according to the other ticket, it should totally behave just like a DS3 (but sensors).

**Comment by nefarius** [comment] 2016-10-09 13:19
@Encryption767 I made some modifications from memory, don't know if it works or crashes, you're invited to test 😄 Feedback welcome.

[FireShock_Setup_1.0.2.exe.zip](https://github.com/nefarius/FireShock/files/518297/FireShock_Setup_1.0.2.exe.zip)

**Comment by Encryption767** [comment] 2016-10-09 15:53
Great work. Anti micro picked everything up right away and I was able to map the device properly. Xbox controller also was picked up and was able to be mapped. 

There is an issue with DPC latency however. With the Fireshock driver installed, the latency begins to climb. I am still testing to see when it happens though. I want to rule out antimicro before I can say for sure.

Latency spikes.
![antimicro](https://cloud.githubusercontent.com/assets/7015014/19221737/8e5ea804-8e0e-11e6-9788-a1a521851600.PNG)

Default.

![default](https://cloud.githubusercontent.com/assets/7015014/19221740/9ebfb1ac-8e0e-11e6-84c0-91e18a93b097.PNG)

**Comment by Encryption767** [comment] 2016-10-09 16:04
Ok. Just tested with the controller plugged in with antimicro running without the fireshock driver installed and all is fine in DPC land.



![antimicroalone](https://cloud.githubusercontent.com/assets/7015014/19221804/1be7e3e2-8e10-11e6-9afe-900ec5a43c7f.PNG)

**Comment by Encryption767** [comment] 2016-10-09 16:10
Just tell me if there is something in particular you need me to test and I will help however I can.

**Comment by nefarius** [comment] 2016-10-09 17:45
Thanks for the feedback. Since I'm fairly new to kernel land it's entirely possible that I've goofed something up. I'll check out the LatencyMon tool on my systems and report back.

**Comment by Encryption767** [comment] 2016-10-09 17:47
Sounds great. If you can clear that up then Fireshock will certainly be well on its way to being a preferred light weight driver.

**Comment by nefarius** [comment] 2016-10-09 17:49
Does the slowdown appear with or without ViGEm or does it not matter?

**Comment by Encryption767** [comment] 2016-10-09 17:49
It appears with and without.

**Comment by nefarius** [comment] 2016-10-09 17:49
Ok, thanks!

**Comment by Encryption767** [comment] 2016-10-09 17:50
Anytime!

**Comment by nefarius** [comment] 2016-10-09 17:51
Hm, what's that on your end?

![](http://content.screencast.com/users/Nefarius/folders/Snagit/media/52b5a11d-aaab-4622-abcb-4e7f14af0904/10.09.2016-19.51.png)

**Comment by Encryption767** [comment] 2016-10-09 17:57
The same for FireShock.sys. USBPORT.sys goes nuts though.

![usbport](https://cloud.githubusercontent.com/assets/7015014/19222514/ef97dd14-8e1f-11e6-9a5c-dd6cedb0218f.PNG)

**Comment by nefarius** [comment] 2016-10-09 17:58
Ha! Well that's something, thanks 😄

**Comment by Encryption767** [comment] 2016-10-09 18:01
Sys specs-
EVGA x79 Dark
EVGA 1080 SC
Corsair Vengeance 32gb ddr3 
Intel Core i7  4820k @ 4.4hgz

**Comment by Encryption767** [comment] 2016-10-09 18:03
USBPORT.sys has tripled since I posted that. I kept Latency mon running since that last post.

![usbport](https://cloud.githubusercontent.com/assets/7015014/19222555/d0105bc8-8e20-11e6-80a4-21df6b609326.PNG)

**Comment by nefarius** [comment] 2016-10-09 18:04
WTF have I done 😕

**Comment by Encryption767** [comment] 2016-10-09 18:06
That's just a DPC count. Could be my system tbh.

I still have it installed and for now all is well. But I am watching it. I am going to try to use it in combination with antimicro.

**Comment by Encryption767** [comment] 2016-10-09 18:31
Something is up for sure. I have mapped a regular ps3 controller out with antimicro but then I closed it out and checked latency mon in the background..

![usbport](https://cloud.githubusercontent.com/assets/7015014/19222717/a8bca0aa-8e24-11e6-85a8-d8f1149f7a07.PNG)

**Comment by Encryption767** [comment] 2016-10-09 19:04
Not sure if this means anything but Kernel-PnP event log shows an error.

Device USB\VID_054C&PID_042F\6&1aad3f20&0&2 could not be migrated.

Last Device Instance Id: USB\VID_045E&PID_028E&IG_01\2&9C6DEB5&3&01
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Location Path: 
Migration Rank: 0xF000FFFF0000F122
Present: false
Status: 0xC0000719

**Comment by johnrossporter** [comment] 2016-10-31 03:49
How did you get Device Manager to recognize the FireShock driver on a PS3 Move Navigator Controller? I tried to edit the  inf with the correct hardware ID's, but it complains about the hashes not being present in the  catalog.

**Comment by Encryption767** [comment] 2016-10-31 09:50
He posted a link to a special version within that thread. Unfortunately, it was doing something wrong under the hood as the DPC latency climbed up and up as long as the driver remained.


________________________________

**Comment by nefarius** [comment] 2016-10-31 10:58
Once these issues are resolved the next release will support the nav controller.

**Comment by Encryption767** [comment] 2016-10-31 20:51
Sounds great nefarius!

**Comment by nefarius** [comment] 2016-11-06 17:33
Oi, I've fixed the latency issues 😄 

![image](https://cloud.githubusercontent.com/assets/286631/20040002/69facb9e-a44f-11e6-8397-549bfbae8546.png)

Nav Controller also integrated; ViGEm interface needs a bit of work then a new release is ready for publishing.

**Comment by Encryption767** [comment] 2016-11-06 19:08
Looking forward to it!

**Comment by nefarius** [comment] 2016-11-06 19:10
You can test this pre-release if you want: [FireShock_Setup_1.1.0.exe.zip](https://github.com/nefarius/FireShock/files/574048/FireShock_Setup_1.1.0.exe.zip)

**Caution:** don't use with current release of ViGEm or system might crash!

**Comment by Encryption767** [comment] 2016-11-06 22:33
I don't have ViGEm installed.

I gave it a test and for the first 5 min all was well.

![antimicro](https://cloud.githubusercontent.com/assets/7015014/20042378/a47dbbd4-a43e-11e6-8936-2b3ee738a394.PNG)

Unplugging and plugging the device has settled the latency down now so I am going to use it for a bit and see if it climbs back up.

**Comment by Encryption767** [comment] 2016-11-06 22:48
Played about 5 min of q3 before it became unbearable. Tried with a regular ds3 controller and have the same issues.

**Comment by mirh** [comment] 2016-11-06 22:56
Then.. I'd *assume* this and #3 are duplicate.

**Comment by Encryption767** [comment] 2016-11-07 07:46
On another note.. when I try to build the driver myself in VS2015, It can not find driver.h from device.h.

If it isn't included with your git version then on your next commit could you include driver.h?

**Comment by mirh** [comment] 2016-11-07 07:52
To compile KMDF/UMDF drivers, you need the [Windows Driver Kit](https://developer.microsoft.com/en-us/windows/hardware/windows-driver-kit)

**Comment by Encryption767** [comment] 2016-11-07 07:52
I have both 8.1 and 10

**Comment by mirh** [comment] 2016-11-07 07:53
Perhaps you need to add the correspondent Include folder?

**Comment by Encryption767** [comment] 2016-11-07 07:55
A quick search reveals no driver.h file. I think this is a file he wrote.

**Comment by mirh** [comment] 2016-11-07 07:59
[Doesn't seem like](https://msdn.microsoft.com/it-it/library/hh706187(v=vs.85).aspx). 
Uh.. Maybe we are talking about 7.1 SDK ?

**Comment by Encryption767** [comment] 2016-11-07 07:59
I certainly hope not.

**Comment by Encryption767** [comment] 2016-11-07 08:00
I never said! I am on Windows 10 x64 with the anniversary update.

**Comment by Encryption767** [comment] 2016-11-07 08:23
Which folder do you have to include mirh?

**Comment by mirh** [comment] 2016-11-07 09:22
I'd guess whatever "Include" one contained in the wdk installation folder. 
Inside Program files (x86)\Microsoft SDKs or Program files (x86)\WDK iirc.

**Comment by JoshWobbles** [comment] 2016-11-07 18:02
Sweet, And I was just going to ask if support was coming for the Nav controller!

**Comment by nefarius** [comment] 2016-11-07 18:24
@Encryption767 @mirh sorry for the confusion; you also need to clone ViGEm into the same parent directory for the build to succeed, the include settings are a bit messy at the moment 👼 

@Encryption767 please ensure you test with version 1.1.0, I can not replicate the latency issues anymore on two different machines of mine:

![image](https://cloud.githubusercontent.com/assets/286631/20070171/b2d44f04-a51f-11e6-930e-c76a1169c9bc.png)

**Comment by Encryption767** [comment] 2016-11-07 19:55
Check out the amount of time you have it connected.

This is after about 4 min or so. I have the driver version showing here.
![antimicro](https://cloud.githubusercontent.com/assets/7015014/20073354/878b44f2-a4f1-11e6-982d-e8e1d1e2b5e9.PNG)


And this is the same session right after uninstalling the driver. I have the device manager open here to show.

![antimicroalone](https://cloud.githubusercontent.com/assets/7015014/20073393/b9a4ec90-a4f1-11e6-8d38-b2e6b3f986a1.PNG)


The original one you sent me earlier in this thread was also 1.1.0. Is there anyway you might have gotten them mixed up with each other and sent me the old one instead?

**Comment by Encryption767** [comment] 2016-11-07 20:03
Very strange. What version of windows are you running? Is it x64?

**Comment by nefarius** [comment] 2016-11-07 20:34
My Windows 10 version (x64):

![image](https://cloud.githubusercontent.com/assets/286631/20074679/8e8f1e8c-a531-11e6-8e7f-056e318daaf5.png)

Try this:

1. Uninstall FireShock
1. Download [RAPR](https://driverstoreexplorer.codeplex.com/)
1. Run as Administrator
1. Select all `Nefarius Software Solutions` entries, check force delete and remove them
1. Re-plug your controller, if it's still showing up as FireShock Device, right click and uninstall from Device Manager
1. Reboot
1. Try again; this is the working build: [FireShock_Setup_1.1.0.exe.zip](https://github.com/nefarius/FireShock/files/576572/FireShock_Setup_1.1.0.exe.zip)

Good luck!

**Comment by Encryption767** [comment] 2016-11-07 20:58
Maybe something is wrong on my end then. I am having this issue still. If someone else would chime in and test then that would be good. Got to play a game with it for at least 4 to 5 min though.

**Comment by nefarius** [comment] 2016-11-07 21:16
Does it occur only with the Nav Controller? Do you have a DS3/4 for testing? I don't have a Nac one so I can't replicate a 100%.

**Comment by Encryption767** [comment] 2016-11-07 21:21
It happens on both the ds3 and the nav. Freed up a USB 3.0 port and I am trying on it now. The previous driver did the same thing on both but so far the usb 3.0 is working properly with the controller. 

Even after 15min, it is still stable.

**Comment by JoshWobbles** [comment] 2016-11-08 12:50
The DS3 fails to start for me using 1.1.0 Status given Code 10: 
The specified request is not a valid operation for the target device.

Possibly related system event log entry:

> Log Name:      Microsoft-Windows-Kernel-PnP/Configuration
> Source:        Microsoft-Windows-Kernel-PnP
> Date:          11/8/2016 7:40:32 AM
> Event ID:      411
> Task Category: None
> Level:         Error
> Keywords:      
> User:          SYSTEM
> Computer:      Josh-Desktop
> Description:
> Device USB\VID_054C&PID_0268\7&242646c2&0&4 had a problem starting.
> 
> Driver Name: oem24.inf
> Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
> Service: HidUsb
> Lower Filters: FireShock
> Upper Filters: 
> Problem: 0xA
> Problem Status: 0xC0000010
> Event Xml:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name="Microsoft-Windows-Kernel-PnP" Guid="{9C205A39-1250-487D-ABD7-E831C6290539}" />
>     <EventID>411</EventID>
>     <Version>0</Version>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Opcode>0</Opcode>
>     <Keywords>0x4000000000000000</Keywords>
>     <TimeCreated SystemTime="2016-11-08T12:40:32.796526100Z" />
>     <EventRecordID>795</EventRecordID>
>     <Correlation />
>     <Execution ProcessID="4" ThreadID="9252" />
>     <Channel>Microsoft-Windows-Kernel-PnP/Configuration</Channel>
>     <Computer>Josh-Desktop</Computer>
>     <Security UserID="S-1-5-18" />
>   </System>
>   <EventData>
>     <Data Name="DeviceInstanceId">USB\VID_054C&amp;PID_0268\7&amp;242646c2&amp;0&amp;4</Data>
>     <Data Name="DriverName">oem24.inf</Data>
>     <Data Name="ClassGuid">{745A17A0-74D3-11D0-B6FE-00A0C90F57DA}</Data>
>     <Data Name="ServiceName">HidUsb</Data>
>     <Data Name="LowerFilters">FireShock</Data>
>     <Data Name="UpperFilters">
>     </Data>
>     <Data Name="Problem">0xa</Data>
>     <Data Name="Status">0xc0000010</Data>
>   </EventData>
> </Event>

**Comment by Encryption767** [comment] 2016-11-08 15:56
If you have a usb 3.0 port then try that. Make sure your drivers are up to date though. 

Both DS3 and Nav are working flawlessly on usb 3.0. I only have trouble if I connect them to a usb 2.0 port.
The DPC latency is great and no crashes since last night.

**Comment by JoshWobbles** [comment] 2016-11-08 20:34
Im not having DPC issues, the driver wont start whatsoever.

**Comment by nefarius** [comment] 2016-11-08 21:54
@JoshWobbles because you have ViGEm installed. As I said earlier don't use v1.1.0 with ViGEm; it will behave exactly like you reported.

**Comment by JoshWobbles** [comment] 2016-11-08 22:15
@nefarius ahhh, i was expecting a BSOD

**Comment by nefarius** [comment] 2016-11-08 22:16
@JoshWobbles not every fault has to result in an instant BSOD 😆

**Comment by JoshWobbles** [comment] 2016-11-08 22:18
@nefarius They do when I write drivers

**Comment by nefarius** [comment] 2016-11-08 22:21
That's why the code is clustered with `if (!NT_SUCCESS(status)) { ... }` statements 😉

**Comment by charlesmilette** [comment] 2016-11-08 22:23
```c#
try {
    stuff.Do()
} catch (Exception exc) {
    // Meh, screw it
}
```

**Comment by nefarius** [comment] 2016-11-08 22:27
I'd applaud M$ if they'd introduce an exception pattern in kernel mode 😆

**Comment by nefarius** [comment] 2016-11-08 23:25
@Encryption767 here's another version where I've added a few more improvements in the critical areas, please test with your 2.0 ports.

[FireShock_Setup_1.1.1.exe.zip](https://github.com/nefarius/FireShock/files/579586/FireShock_Setup_1.1.1.exe.zip)

**Comment by JoshWobbles** [comment] 2016-11-09 11:30
Have not had a chance to test with latency mon, but hardware definately became verry laggy after a couple minutes (mouse most noticeably) when using Nav controller on USB 2.0. Unplugged the controller and all went back to normal.

**Comment by Encryption767** [comment] 2016-11-09 13:44
I look forward to testing here later today. I have some things to take care of this morning but I will reply with what I find later today.

**Comment by JoshWobbles** [comment] 2016-11-09 20:07
This is after a couple minutes with it plugged in, returns to normal afterward.
![Latency](http://content.screencast.com/users/jhebbel/folders/Snagit/media/81799085-a593-452e-8d5a-c9a5148d384e/11.09.2016-15.06.png)

**Comment by nefarius** [comment] 2016-11-11 16:53
*scratches head*

**Comment by mirh** [comment] 2016-11-11 19:20
Juuust for the records, if you use [Windows Performance Toolkit](http://www.msfn.org/board/topic/140263-how-to-get-the-cause-of-high-cpu-usage-by-dpc-interrupt/) and you load symbols, you can see with a huge precision which functions is causing all the calls.

**Comment by nefarius** [comment] 2016-11-11 21:37
@mirh I already tried it but either I'm not skilled enough to interpret it or it's just not fine enough:

![image](https://cloud.githubusercontent.com/assets/286631/20231049/6c8ef6c8-a85f-11e6-9a8e-3b485187b2ab.png)

**Comment by mirh** [comment] 2016-11-11 23:11
Uh?
I thought you weren't experiencing the thing?

**Comment by nefarius** [comment] 2016-11-11 23:44
The capture is from an earlier release; now I can indeed not replicate it but I poked in the dark before even with the performance toolkit assisting me.

I'll have no other choice i guess than disabling chunks of the code until I find another clue. Oh boy...

**Comment by charlesmilette** [comment] 2016-11-12 00:00
I pity you.

**Comment by mirh** [comment] 2016-11-12 11:27
Wtf?
My suggestion was to ask @Encryption767 and @JoshWobbles to provide you with a log.

**Comment by nefarius** [comment] 2016-11-12 11:44
Oh ah yeah, makes sense 😆 Shouldn't stay up too long I guess 🍷

**Comment by nefarius** [comment] 2016-11-13 10:49
I left a DS3 and a DS4 connected and left it running the whole night, here are my results:

![2016-11-13](https://cloud.githubusercontent.com/assets/286631/20245017/f815c612-a996-11e6-8396-30ad3840b867.png)

![2016-11-13 1](https://cloud.githubusercontent.com/assets/286631/20245020/fdaa5b42-a996-11e6-8f8d-3d06b0c1f8c8.png)

![2016-11-13 2](https://cloud.githubusercontent.com/assets/286631/20245021/018ef29a-a997-11e6-8db1-619ef8638469.png)

So if you still experience problems I'm afraid I have to count on your debugging skills 😮

**Comment by JoshWobbles** [comment] 2016-11-14 17:36
My weekend was packed and my main pc is busy rendering 4k videos, ill make an attempt when I can.

**Comment by JoshWobbles** [comment] 2016-11-17 13:37
Ok, so weird, Im coming off of a reset reset because my windows update database "somehow" decided to corrupt itself, and now I cannot replicate. Could be conditional based on somthing else I had plugged in or installed, will have to systematically get my PC back up to what it was before and see if it has issues at any point along the way.

**Comment by JoshWobbles** [comment] 2016-11-17 14:25
scratch that, it took a bit longer but its definitely still happening. Here is my log https://1drv.ms/u/s!AnvwSUr7_fTqgpI_Z4JGsfpCtN2epQ

**Comment by nefarius** [comment] 2016-11-20 10:53
@JoshWobbles do me a favour, just so we can rule this out; adjust your build settings like so:

![image](https://cloud.githubusercontent.com/assets/286631/20462247/cd16d286-af17-11e6-8846-62513f212213.png)

and try again please. If the error persists, try with 19 instead of 15 too please.

**Comment by JoshWobbles** [comment] 2016-11-20 11:28
Im not building my own, ive been using your releases

**Comment by nefarius** [comment] 2016-11-20 11:29
Oh ok, didn't know that, I can craft one for you then.

**Comment by JoshWobbles** [comment] 2016-11-20 11:33
For clarification, 1.0.0 worked fine, 1.1.0 and 1.1.1 had the DPC issues on USB 2.0 using either a move or PS3 controller

**Comment by nefarius** [comment] 2016-11-20 11:34
W00t?! I hate it when that happens... Looking through the commits then...

**Comment by JoshWobbles** [comment] 2016-11-21 17:12
Any luck making heads or tails of that log?

**Comment by nefarius** [comment] 2016-11-21 18:13
I have a few suspicions but my weekend was packed with other tasks and I have to finish the redesigned ViGEm interface too so it's slow progress, nothing major to report so far except I'd wanna try it with a more recent version of the WDF libs, *maybe* I've hit a strange bug.

**Comment by nefarius** [comment] 2016-11-21 20:13
@JoshWobbles in the meantime: what's the value of `KmdfLibraryVersion` in `HKLM\System\CurrentControlSet\Services\FireShock\Parameters\Wdf` on your system?

**Comment by JoshWobbles** [comment] 2016-11-21 20:15
1.15

**Comment by nefarius** [comment] 2016-11-21 20:18
Damn

**Comment by Alia5** [comment] 2016-11-21 20:53
Tried with both, 1.0.1 and 1.1.1
Everything seems fine here
![2016-11-21_2152](https://cloud.githubusercontent.com/assets/3527662/20500227/e8ce2a10-b034-11e6-9335-58457b1dcd61.png)

**Comment by JoshWobbles** [comment] 2016-11-21 20:55
I must have an incompatibility somewhere, ill run again and unplug random parhipreals/stop processes and see if anything other than removing the nav controller stops it

**Comment by Alia5** [comment] 2016-11-21 20:59
"Edit:" One thing to note though, is that plugging in a DS3 crashes my USB-Fancontroller application
The issue here is probably on my end since the code is god awful.

Could this nonetheless hint to some problems with other HID devices/controll applications?

**Comment by JoshWobbles** [comment] 2016-11-21 21:08
@nefarius ok, so it seemed to be an "overloaded" bus on my end, took my BT dongle for my mouse to a different bus and no more DPC leaks, so this explains why I was getting it and none of the other guys in here, but could result in a pretty decent number of users once it becomes more widely adopted. Knowing exactly zip about c++ development and only able to draw from what I know in c#, feels like a dispatcher overload due to too many concurrent calls, not sure what the fix is in this situation, but in c# would involve a dispatcher queue or timeout implementation.

But either way good to know that I can work around it.

**Comment by JoshWobbles** [comment] 2016-11-21 21:44
I lied.... Its back.... This is why Id suck as a beta tester. USB 2.0 port, only device on bus now and it starts climbing almost immediately.

**Comment by nefarius** [comment] 2016-11-28 09:26
@JoshWobbles heya! How's this one doin' for ya? [FireShock_Setup_1.1.3.exe.zip](https://github.com/nefarius/FireShock/files/615853/FireShock_Setup_1.1.3.exe.zip)

**Comment by JoshWobbles** [comment] 2016-11-28 11:54
@nefarius Sweet, an early Christmas present! Im going to let it run for most the day so I dont put my foot in my mouth again, but early indications with the Nav controller are problem solved, will try with a DS3 in a while on various USB ports aswell.

**Comment by JoshWobbles** [comment] 2016-11-28 12:07
Ok so it was good for a while, then I picked it up and started mashing controls and "using" it and the DPC slowly started to rise, I then unplugged it and my DPC dropped back to normal then plugged it back in and DPC started to rise again only this time immediately and without mashing on buttons. If it were c# id say garbage collector but since c++ doesn't have one of those....

I will reboot and see if the behavior is reproducible specifically DPC being low until initial use then climbing after use even after subsequent reconnects.

**Comment by nefarius** [comment] 2016-12-01 16:52
Nothing wrong with your usage of the library. Hm...

**Comment by nefarius** [comment] 2017-01-19 20:38
Sorry this took so damn long, but the new signing procedures are just ridiculous and slow as hell 😠 Anyways, here's a new version which should work fine even in UEFI Secure Boot Mode: [1940597.zip](https://github.com/nefarius/FireShock/files/717719/1940597.zip)

**Comment by JoshWobbles** [comment] 2017-01-20 00:00
Ill give it a shot in a bit!

**Comment by charlesmilette** [comment] 2017-01-20 00:08
@nefarius I'd suggest you to generate a certificate yourself to sign the driver.

You could pass us the public key so we can add it to our root certificate store and test the driver without waiting for M$ to sign your experimental driver.

**Comment by JoshWobbles** [comment] 2017-01-20 00:11
Do self signed drivers work in Win 10?

**Comment by nefarius** [comment] 2017-01-21 16:13
@JoshWobbles @charlesmilette nope, the kernel doesn't use the trusted root store so you can't bypass it. Only (not recommended) working workaround is turning on test mode.

**Comment by charlesmilette** [comment] 2017-01-21 16:20
:(

**Comment by JoshWobbles** [comment] 2017-01-25 16:39
@nefarius So that latest drivers throws "This device cannot start. (Code 10)
The specified request is not a valid operation for the target device."

**Comment by nefarius** [comment] 2017-01-25 17:19
@JoshWobbles 😄 was worried there for a second...

**Comment by JoshWobbles** [comment] 2017-01-25 17:19
I will note however, same climbing DPC issues

**Comment by nefarius** [comment] 2017-01-25 17:20
Odd, odd, odd...

**Comment by JoshWobbles** [comment] 2017-01-25 17:20
Actually seemed even quicker this time

**Comment by nefarius** [comment] 2017-01-25 17:20
I literally ran out of ideas 😕

**Comment by JoshWobbles** [comment] 2017-01-25 17:20
Im going to put it on my streaming server see if I can duplicate

**Comment by JoshWobbles** [comment] 2017-01-25 18:32
Shit, so server works fine with it, so it must be an incompatibility with my PC either hardware or driver.

**Comment by JoshWobbles** [comment] 2017-01-28 12:33
I have users reporting with my alpha release that they are seeing the same "leak" issue, so its not everybody, but it does seem to be reproducible.

**Comment by 252rer** [comment] 2017-04-13 05:22
Now this is strange, I had been running  FireShock 1.1.3 for a few days with no problems then today I noticed the computer slowing down with just the controller plugged in. System interrupts climbing in cpu usage quickly too. I noticed windows say it was setting up the device when I first plugged it in today which had happened a few times if memory serves(always same usb port). USBPORT.sys shows in latency check, unplugging controller returns system to normal.

**Comment by nefarius** [comment] 2017-04-15 14:01
I have an idea how to fix this but it'll take me a few days.

**Comment by Vebryn** [comment] 2017-06-05 09:11
Same problem using FireShock 1.3.1.0, I'm going to try with older version.

**Comment by 252rer** [comment] 2017-06-16 02:40
Rebooting after first controller plug in install usually fixes for me.

**Comment by Vebryn** [comment] 2017-06-18 08:49
Hopelessly not for me :s

**Comment by nefarius** [comment] 2017-06-20 18:39
F*ck it, I rewrite it 😠

**Comment by JoshWobbles** [comment] 2017-06-20 18:42
If i recall correctly, v1.0.0.0 DS3 worked fine, shortly after the inclusion of the nav controller I started getting the BSODs when using any DS3 or Nav controller.

**Comment by nefarius** [comment] 2017-06-20 18:52
Seriously, I can't find the error. Maybe the DS3 has some serious problem when using a filter driver so I'm ditching this and write a proper function driver. This will take me a while but at least I then have full control over the controller.

**Comment by mirh** [comment] 2017-06-20 19:21
And.. aside of this more or less solvable issue, would there be any gain?

**Comment by JoshWobbles** [comment] 2017-06-20 19:25
@mirh You solved this?

**Comment by mirh** [comment] 2017-06-20 19:30
The most testing I did was trying to install this on Vista (which succeeded!) :s
I'd help but unfortunately I'm low on time. 

Anyway, I find very hard to believe that with a fully blown Windows Performance Toolkit analysis (from the people having the problem I guess, given afaiu nefarius cannot reproduce the thing), one shouldn't be able to find the root cause.

**Comment by JoshWobbles** [comment] 2017-06-20 19:33
@mirh I uploaded one in Nov but I think it was inconclusive.

**Comment by mirh** [comment] 2017-06-20 19:45
Did you use all the [right](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/example-15--measuring-dpc-isr-time) flags?

**Comment by JoshWobbles** [comment] 2017-06-20 19:51
@mirh I have no idea what I typed this morning let alone 8 months ago lol

**Comment by mirh** [comment] 2017-06-20 20:09
I think a verbose CPU usage and Minifilter I/O activity should be enough.

**Comment by luisdecker** [comment] 2017-07-24 00:18
Just for information: I had the excessive cpu consumption problem with FireShock, leading to a system hang and all. The solution I found was to change the USB port in my laptop (from a 2.0 to a 3.0). Using latest (1.3.1.0) FireShock driver. 😄 With the same configuration, changing the usb port makes the cpu usage go up.

**Comment by 252rer** [comment] 2017-10-11 16:10
Is anyone still having this issue after the last 4 or so windows updates to do with usb in the last couple months? The latest OS Build 15063.674 on October 10th fixed a rather major one.

**Comment by mirh** [comment] 2017-10-11 18:20
If that's it, I think we are soon going to have a new linux kernel developer on the market

**Comment by nefarius** [comment] 2017-10-12 18:00
Hm?

**Comment by mirh** [comment] 2017-10-12 18:28
Isn't it like a year that someone is banging his head to get around some wtf issue?

**Comment by nefarius** [comment] 2017-10-12 18:46
Nah, I switch between different projects and games to cool off and since I wasn't affected personally, well... I'm not a wizard 😉

**Comment by 252rer** [comment] 2017-10-14 02:14
Welp had happen again today, but fixed by just uninstall and reinstalling.

**Comment by 15wileyr** [comment] 2017-10-25 22:01
Yeah I'm Having this issue!!

**Comment by nefarius** [comment] 2017-10-25 22:02
@15wileyr this won't happen anymore in my rewrite.

**Comment by 15wileyr** [comment] 2017-10-25 22:07
Oh Snap! where/when is this rewrite?

**Comment by nefarius** [comment] 2017-10-25 22:08
I'm currently writing the "Scp replacement" for it but the driver itself is finished and working fine.

**Comment by 15wileyr** [comment] 2017-10-25 22:09
Is there anywhere I can download just the driver currently? All I want is the dinput functionallity.

**Comment by nefarius** [comment] 2017-10-25 22:11
The driver won't work without the backend service and `ViGEm` so a binary alone wouldn't help you much.

**Comment by 15wileyr** [comment] 2017-10-25 22:12
Oh okay thanks I'm a noob. So will the release force xinput with ViGEm bc that would ruin the utilty for me.

**Comment by nefarius** [comment] 2017-10-25 22:14
No, you can emulate the DS3 as either DS4 or X360 controller, your free choice.

**Comment by 15wileyr** [comment] 2017-10-25 22:22
Will that be It's own Project?

**Comment by nefarius** [comment] 2017-10-25 22:22
Yes, I just created the repo today.

**Comment by 15wileyr** [comment] 2017-10-25 22:31
Okay this is my last question, what's it called? I'm having trouble finding it so I can keep checking back until release. Also, thank you for taking the time to answer my questions and for your work, ScpTK provided so much fun and utility, it made the world a little bit better.

**Comment by nefarius** [comment] 2017-10-25 22:32
Glad to hear 😄 [It's here](https://github.com/nefarius/Shibari), I'm working full throttle on it.

**Comment by 15wileyr** [comment] 2017-10-25 22:34
Godspeed sir

**Comment by nefarius** [comment] 2017-10-25 22:35
I should probably go to sleep but I' setting up a server and Windows Update takes ages... 😟

**Comment by nefarius** [comment] 2017-12-25 17:28
Version 1.x is obsolete and so are related issues. v2 will be published soon™.

**Closed by nefarius** 2017-12-25 17:28 UTC
Labels: bug, enhancement
